name: fitness
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9  # updated

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1  # updated

flutter:
  uses-material-design: true
  assets:
  
  - assets\icons\Filter.svg
  - assets\icons\Search.svg
  - assets\icons\dots.svg
  - assets\icons\pie.svg
  - assets\icons\plate.svg
  - assets\icons\salmon-nigiri.svg
  - assets\icons\arrow.svg
  - assets\icons\blueberry-pancake.svg
  - assets\icons\button.svg
  - assets\icons\canai-bread.svg
  - assets\icons\honey-pancakes.svg
  - assets\icons\orange-snacks.svg
  
